### ISSUE TITLE
[버그] 임베드 이미지 오류

### ISSUE THREAD

**Issue by MadeGOD** [koreanbots/serverlist-testing#33]
# 버그 설명
임베드 사진이 로딩되지 않습니다

# 재현방법
임베드 사진을 정상적으로 로딩하게 합니다.
...
# 예상한 동작
정상적으로 로딩되야 합니다.
...

# 클라이언트 정보

- 브라우저(버전): 
- OS: Android 7
- 기기: Samsong

# 발생되는 페이지

https://beta.koreanbots.dev/servers/{id}

# 첨부파일
![Screenshot_20210905-155918](https://user-images.githubusercontent.com/63600304/132119933-050ca755-6dea-4749-98e7-57c3f90263d4.jpg)

**Comment by samsunghappytree123** [comment]
![image](https://user-images.githubusercontent.com/58595445/132119969-80e136c2-91a6-472d-a944-207ac1703f1b.png)

**Comment by wonderlandpark** [comment]
NAB, Intended
